### ISSUE TITLE
Storage for MatrixMarket collections

### ISSUE THREAD

**Issue by kirill-terekhov** [INMOST-DEV/INMOST#10]
Complete set of real matrices from MatrixMarket [http://math.nist.gov/MatrixMarket/](http://math.nist.gov/MatrixMarket/) takes 700mb of space. When archived with tar.gz they take 148mb.

I suggest we include a tiny subset of matrices into repository and put the rest to dodo.inm.ras.ru or cluster. Then on cmake there would be an option to activate the full set and the user would have to download the set and put it to prescribed folder. Where would it be appropriate to store the archive with the set?

I suggest you also consult with Konshin and Kaporin on which matrices to take into tiny subset so that they are representative of solver robustness.

This is related to solver_test001.

**Comment by a-a-danilov** [comment]
First of all, you may take a look at Florida Univ. Sparse Matrix Collection http://www.cise.ufl.edu/research/sparse/matrices/
It looks like this collection include the MatrixMarket collection.

I suggest downloading matrices directly from original sources, otherwise we should ask the permissions to host the files.

If you need to place some supplementary files, you can put them on dodo in `/home/inmost`, these files will be accessible via http://dodo.inm.ras.ru/inmost/

**Comment by kirill-terekhov** [comment]
Florida's collection is too huge.


I think it should be automatized as much as possible. Maybe we should establish small representative subset of matrices and write script for cmake that will download those matrices, unpack and execute tests?

**Comment by a-a-danilov** [comment]
If you are willing to prepare such script, then go ahead. Start with any subset you like. If you have already encountered some problems in internal solver with some matrices, include them.

**Comment by kirill-terekhov** [comment]
The issue is that some problems may take quite a lot of time. Do we want the user to wait half a day for internal testing?


This one test is more relevant to "Benchmarking" category which should be activated separately, results systemized and shared online along with machine information for statistics. Something like this [http://www.icm.tu-bs.de/~bolle/ilupack/iluhtmls/collection.shtml](http://www.icm.tu-bs.de/~bolle/ilupack/iluhtmls/collection.shtml). That's quite a lot of work so should be postponed for later times as a very nice enhancement.


And for the solver_test001 It would be more appropriate to generate some simple, yet nontrivial matrix (not a diagonal one as in permutation test) to test that solvers and preconditioners are functional. Something that breaks simple ILU0 and don't converge on pure GMRES/BCGS(L) so that to ensure that preconditioner is the working horse. This will greatly protect us from introducing any bugs in development of solvers.


As for the robustness on the problems: I encountered problems on which only INNER_MLILUC is functional but there is a problem (sparsekit collection | drivcav | e40r2000) with huge condition number in inverse factors for which INNER_MLILUC requires very fine tuning of one parameter but Aztec+Ifpack solves it out of the box. I suspect that ifpack just knows the kind of the problem and applies something like maximum transversal on it. I know how to overcome the issue in the INNER_MLILUC and let it tune automatically, but it may be more computationally expensive and requires lots of work.
