### ISSUE TITLE
Failure Compiling ParMETIS on Windows

### ISSUE THREAD

**Issue by wurunjian** [INMOST-DEV/INMOST#14]
I followed this wiki instruction "Compiling INMOST with ParMETIS on Windows" (
https://github.com/INMOST-DEV/INMOST/wiki/0204-Compilation-ParMETIS-Windows)
to compile Parmetis on windows using CMake. But I got the error below.
"failed to create symbolic link 'metis': No error

Looking for execinfo.h
Looking for execinfo.h - not found
Looking for getline
Looking for getline - not found
Configuring done

Then I compile ParMETIS.sln in Visual Studio. I got many errors (See below).
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\math.h(515): error C2059: syntax error : '(' 

My Windows Environment: Windows 8.1, Visual Studio 2013, CMake 3.4.0, MPICH2, parmetis-4.0.3.

Have you met this before? Can you help me solve this problem?

Thanks,

**Comment by kirill-terekhov** [comment]
Besides that CMake haven't reported that it had found MPI library, I don't see any problem in it's output.

Although unlikely that MPI causes the problem, you may check that you have MPI variables defined in CMake, check "Advanced" box and type "MPI_" into search. You should have MPI_CXX_INCLUDE_PATH, MPI_C_INCLUDE_PATH, MPI_CXX_LIBRARIES, MPI_C_LIBRARIES defined (that what I have).

You may try to go to the problematic file that includes "math.h". You should see that file in Output pane of Visual Studio (here how to open it: https://msdn.microsoft.com/en-us/library/3hk6fby3(v=vs.120).aspx) and try to move the include statement to the top before all the other includes in this file.

If the problem persists you'd better ask developers of ParMetis to address it: http://glaros.dtc.umn.edu/flyspray/index.php?tasks=all&project=2

**Comment by wurunjian** [comment]
Thank you very much! I will try that.

**Comment by kirill-terekhov** [comment]
I suggest you post here the solution, once you solve it.
Then I'll put a link from wiki article to this issue.

**Comment by wurunjian** [comment]
Sorry for that. I tried, but I don't know how to move the include statement to the top before all the other includes in this file. There are many head files.

**Comment by kirill-terekhov** [comment]
Could you tell which file is that?
Just cut and paste `#include <math.h>` statement above (or below, however it appears) `#include <mpi.h>`

**Comment by wurunjian** [comment]
I searched #include <math.h>, and found it in GKlib.h. I moved it below #include <float.h>, but I got the same errors.

**Comment by wurunjian** [comment]
I prepared to switch to Linux, and it is easy to configure.

**Comment by wurunjian** [comment]
Hi,Kirill. I followed the https://github.com/INMOST-DEV/INMOST/wiki/0201-Obtain-MSVC to change to VS2010, and it worked now. Thank you very much!

**Comment by kirill-terekhov** [comment]
What kind of Visual Studio 2013 you had? Was it express edition or professional?

**Comment by wurunjian** [comment]
Visual Studio Ultimate 2013

**Comment by kirill-terekhov** [comment]
Ok, I'll give it a try later. Thank you for the report.

**Comment by wurunjian** [comment]
Thank you.

**Comment by kirill-terekhov** [comment]
To fix the problem with Visual Stuido 2013 you should open the file `metis/GKlib/gk_arch.h`,
search for the second occurance of `#ifdef __MSC__` and replace it with `#if _MSC_VER < 1700` then I'm able to compile it with Visual Studio Express 2013.

**Comment by wurunjian** [comment]
It also worked for me. Thank you very much!
