### ISSUE TITLE
Проблема со сборкой INMOST

### ISSUE THREAD

**Issue by xaligali** [INMOST-DEV/INMOST#16]
Следовала инструкции сборки INMOST в windows (https://github.com/INMOST-DEV/INMOST/wiki/0203-Compilation-INMOST-Windows). С помощью cmake успешно собрала проект, но при компиляции возникают ошибки:

Error	1	error C2065: 'uint64_t' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	496	1	inmost
Error	2	error C2146: syntax error : missing ';' before identifier 'mant'	d:\gal\inmost\inmost.pages\source\io\io.hpp	496	1	inmost
Error	3	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	496	1	inmost
Error	4	error C2061: syntax error : identifier 'uint64_t'	d:\gal\inmost\inmost.pages\source\io\io.hpp	496	1	inmost
Error	5	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	498	1	inmost
Error	6	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	499	1	inmost
Error	7	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	500	1	inmost
Error	8	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	501	1	inmost
Error	9	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	502	1	inmost
Error	10	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	503	1	inmost
Error	11	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	504	1	inmost
Error	12	error C2065: 'uint32_t' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	519	1	inmost
Error	13	error C2146: syntax error : missing ';' before identifier 'mant'	d:\gal\inmost\inmost.pages\source\io\io.hpp	519	1	inmost
Error	14	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	519	1	inmost
Error	15	error C2061: syntax error : identifier 'uint32_t'	d:\gal\inmost\inmost.pages\source\io\io.hpp	519	1	inmost
Error	16	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	521	1	inmost
Error	17	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	522	1	inmost
Error	18	error C2065: 'mant' : undeclared identifier	d:\gal\inmost\inmost.pages\source\io\io.hpp	523	1	inmost

Моя среда: Windows 7, Visual Studio Professional 2013, CMake 3.4.3, MPICH2, parmetis-4.0.3.

Поискала решение проблемы: говорят, что нужно использовать вместо библиотеки stdint.h библиотеку cstdint. При замене ошибок еще больше

Можете, пожалуйста, помочь с решением?

Установила Visual Studio Professional 2010, с ней все работает

**Comment by kirill-terekhov** [comment]
Попробовал с Visual Studio Express 2013, компилируется без ошибок.

Посмотри пожалуйста с изменениями, получится или нет.

**Comment by xaligali** [comment]
Все получилось, спасибо!
