### ISSUE TITLE
The local ID's of mesh elements are not reassigned after ReorderEmpty.

### ISSUE THREAD

**Issue by kap-ivan** [INMOST-DEV/INMOST#19]
I expect that the local ID numbers will be reassigned and elements will be numbered sequentially. Otherwise this local ID seems quite useless and confusing. In this case it's not clear how Mesh->ElementByLocalID should work.

**Comment by kirill-terekhov** [comment]
Take a look at [Storage::DataLocalID()](http://www.inmost.org/Doxygen/html/class_i_n_m_o_s_t_1_1_storage.html#a4112611429fe0c871f97392b22b8a86b) - it has contiguous enumeration.
