### ISSUE TITLE
Вложенные сетки

### ISSUE THREAD

**Issue by as-92** [INMOST-DEV/INMOST#22]
Доброго дня!
Можно ли где-нибудь познакомиться с порядком использования вложенных сеток в ИНМОСТ (8-деревья)? И правильное ли это место для общих обсуждений для "внешних" пользователей?

С уважением, Соловьёв Андрей Валерьевич
ИБРАЭ РАН
solovjev@ibrae.ac.ru
as92@yandex.ru

**Comment by kirill-terekhov** [comment]
Здравствуйте, Андрей!

В репозитории INMOST в Source/Examples/OctreeCutcell лежит визуальный пример с динамическим генератором сеток типа 8-деревья со сколотыми ячейками. Я этой задачей сейчас не занимаюсь и документацию по компиляции и использованию этого примера не писал.

В группе Юрия Викторовича Василевского возможно есть подобный код с документацией. Ставлю его в копию и рекомендую обратиться.
