### ISSUE TITLE
The Element::Boundary() function doesn't work properly for Ghost faces.

### ISSUE THREAD

**Issue by kap-ivan** [INMOST-DEV/INMOST#24]
I assume that this function should return the correct indicator of face on boundary residence. The user does not need to think of the aspects of mesh partitioning here.

**Comment by kirill-terekhov** [comment]
There is a function Mesh::MarkBoundaryFaces (https://github.com/INMOST-DEV/INMOST/blob/master/Source/Headers/inmost_mesh.h#L3075) that is designed to solve this issue in parallel. It communicates to other parts of the mesh and marks all the boundary faces of the global mesh.

**Comment by kap-ivan** [comment]
Yes, I use this function now. In my opinion this may be regarded only as a temporary fix. I haven't seen any warnings about the usage of Element::Boundary() in parallel, thus any new user may encounter this error without any idea why it happens.
