### ISSUE TITLE
PETSc UNABLE to CONFIGURE with GIVEN OPTIONS

### ISSUE THREAD

**Issue by CloudComputer** [INMOST-DEV/INMOST#32]
![11](https://user-images.githubusercontent.com/14849839/38005423-1e0f28fc-3273-11e8-889e-4f10ddf76ba0.png)

**Comment by CloudComputer** [comment]
--with-mpi-lib=['/cygdrive/d/MSMPI/Lib/amd64/msmpi.lib'] and
--with-mpi-include=['/cygdrive/d/MSMPI/Inc/'] did not work

**Comment by kirill-terekhov** [comment]
What about contents of configure.log? Maybe it is unable to start a program with mpirun?

Could you please tell how do you use INMOST?

**Comment by CloudComputer** [comment]
I followed the instruction at
[https://github.com/INMOST-DEV/INMOST/wiki/0206-Compilation-PETSc-Windows](url)
and my environment is
win10, MSVC2012
and I build 32-bit binaries.

**Comment by hnhien** [comment]
Hi, I also got the same problem when I tried to compile PETSc with MS-MPI (v10) on win10 (32bit) using VS2013 following the same guideline.

I am not very clear about 64-bit library.
My Intel Parallel Studio XE2013 has to command modes: ia32 & intel 64 VS 2013 modes.
Also, I tried both Cygwin 32 & 64 bit.

If anyone solved this problem, please share it with me!
Thanks!
