### ISSUE TITLE
Problems with INMOST Split Functions

### ISSUE THREAD

**Issue by APlenkin** [INMOST-DEV/INMOST#36]
Далее сперва подробно по проблеме, но не уверен, что это все полезно, в конце напишу тезисно. Можно сперва тезисную часть прочитать.

Итак:
1) Падение происходит внутри функции Face::SplitFace
режется грань с вершинами
15170.170898 13085.651367 25.000000
15212.180664 13180.641602 25.000000
15230.162127 13325.011083 25.000000
15213.287379 13257.682323 25.000000
15207.938294 13236.339946 25.000000
15224.667770 13303.089083 25.000000
15221.901993 13292.053873 25.000000
ребром
15221.901993 13292.053873 25.000000
15213.287379 13257.682323 25.000000
Данные в целом можно не смотреть, грань уже кривая, но
ПАДАТЬ НЕ ДОЛЖНО. Функция должна возвращать код ошибки, а если уж падать, то выводить подробный лог данных по которым можно понять суть проблемы.

2) теперь вопрос а почему грань кривая?
а по тому что INMOST ее такой сделал.
испортил он ее ранее при вызове функции Edge::SplitEdge
при этом получается, что топология которая нарушилась с точки зрения функции SplitFace нарушилась в SplitEdge, а значит именно SplitEdge должен был сгенерировать ошибку, чего не случилось

3) теперь к сути SplitEdge вызывается для ребра
15230.162127 13325.011083 25.000000
15170.170898 13085.651367 25.000000
и для разрезания передаются точки
15213.287379 13257.682323 25.000000
15207.938294 13236.339946 25.000000
15224.667770 13303.089083 25.000000
15221.901993 13292.053873 25.000000
Сейчас задним умом уже можно сказать, что функции почему то важен порядок точек разрезания иначе она делает ерунду и создает ребра с самоналожением.
Это условие во первых нигде не указано, во вторых на мой взгляд такие проблемы упорядочивания должны решаться один раз внутри инмоста, а не кучей пользователей при каждом вызове. Особенно с учетом отсутствия документации. Меня устроит если это будет сделано под доп параметром функции, чтобы не замедлять стандартный режим работы там, где он всех устраивает.
 
Тезисно, что хочется:

   1) сделать работу Edge::SplitEdge робастной убрав неявное требование упорядоченности массива узлов для разбиения.
    собственно тут 3 варианта:
    а) просто добавить нужную сортировку внутрь функции, вроде ничего не должно быть сложного, но я вот сходу не пойму: достаточно ли просто массив упорядочить или еще надо согласовать с порядком узлов в разрезаемом ребре?
    б) добавить сортировку под условие нового параметра функции, чтобы не замедлять стандартную работу.
    в) сделать новую функцию Edge::SplitEdgeCleaver которая и отсортирует и побьет стандартной и может еще что полезное, но медленное.
    2)Сейчас ощущение, что Edge::SplitEdge имеет недостаточно проверок, поскольку геометрию портит именно она, а падает уже Edge::SplitFace
    3)Убрать падения, на миллионной сетке, локализовать источник при таком поведении проблемматично. Варианты:
    а) если функция обнаружила проблему — пусть ничего не делает, а возвращает код ошибки
    б) если уж падать, то выдавать подробный лог какая функция упала, входные данные и что с ними не так.

Критично быстро доработать пункт 1, остальное хотелки, хотя они и сильно сэкономят время в будущем. И да еще раз, можно это сделать и вовне, но это куча мест, неочевидно, что это надо делать, и не до конца очевидно как.

**Comment by kirill-terekhov** [comment]
1. Функция SplitEdge принимает на вход траекторию. Эта траектория не обязательно прямая. Сортировка узлов приведет к изменению траектории. В частности, скорее всего, перестанет работать пример срезания сетки по заданной функции. Действительно, отсутствует детальная doxygen-документация для этих функций. Надо будет добавить, но есть обычный комментарий о том, что узлы должны быть упорядочены.

2. Проверки активируются по SetTopologyCheck, они в том числе выполняются внутри Split* функций. Проверка на самопересечение элементов не реализована. 

3. Чтоб не выдавало исключение в случае срабатывания проверки на топологию нужно вызвать RemTopologyCheck(THROW_EXCEPTION). Чтобы узнать при какой проверки упало SetTopologyCheck(PRINT_NOTIFY).|  В большинстве случаев элемент к моменту проверки уже создан, чтобы он был помечен надо вызвать SetTopologyCheck(MARK_ON_ERROR). Эти фичи в коде задокументированы, но в doxygen по какой-то причине не попадают. Где упало можно узнать из-под debug'а. Дебажить код надо на сетках малого размера. 

Ну, и это вообще-то исследовательский код.

**Comment by APlenkin** [comment]
По 1 не очень понятно. Функция split по названию должне разделять. разделить ребро множеством точек на жтом ребре, так чтоб не было самоналожений, можно единственным способом. Если есть функционалзделать вставку ломаной с концами в точках ребра, то это уже что то совсем другое. 
В той версии кода, который есть в GeRa я никаких комментариев об упорядоченности не нашел (я искал). Опять же даже если б они были, то не понятно, как должны соотноситься порядок точек в исходном ребре и точек в массиве.
В результате с текущей функцией на практике работать совершенно неудобно. Если не хочется трогать текущую, то я как раз предлагаю сделать альтернативную или добавить параметр.

По остальным пунктам... Я вот не уверен, я когда в последний раз обращался с какой то проблемой, ты тоже предложил включить проверки топологии. Либо я что то не так сделал, Либо что то не так работает, но они в проблемной ситуации ничего не выдали.

**Comment by kirill-terekhov** [comment]
https://github.com/INMOST-DEV/INMOST/blob/534d7a34f3fcad0539a435310addee9e4953155a/Source/Headers/inmost_mesh.h#L551

Я могу подсказать тебе, как отсортировать узлы, если это то что ты хочешь.

Проверка на самопересечение элементов не реализована.

**Comment by APlenkin** [comment]
Я хочу, чтобы была реализована функция в INMOST которая содержит внутри это упорядочивание.
Это может быть новая функция.
Если объяснишь алгоритм упорядочивания - я могу ее и сам написать.
Важно, для меня, что бы она так или иначе была добавлена в INMOST.
Каждый раз отдельно прописывать это упорядочивание в разных местах перед каждым вызовом функций INMOST в разных местах крайне неудобно.

**Comment by kirill-terekhov** [comment]
Тебе надо добавить в код такой класс (не проверял):
class OrderNodesAlongEdge
{
	Mesh * m;
	double v[3];
public:
	OrderNodesAlongEdge(Mesh * m, Edge e) :m(m) 
	{
		v[0] = e.getEnd().Coords()[0] - e.getBeg().Coords()[0];
		v[1] = e.getEnd().Coords()[1] - e.getBeg().Coords()[1];
		v[2] = e.getEnd().Coords()[2] - e.getBeg().Coords()[2];
	}
	OrderNodesAlongEdge(const OrderNodesAlongEdge & other) 
	: m(other.m) { std::copy(v,v+3,other.v); }
	OrderNodesAlongEdge & operator=(OrderNodesAlongEdge const & other) 
	{ m = other.m; std::copy(v,v+3,other.v); return *this;}
	int Compare(const double * a, const double * b) const
	{
		double e = m->GetEpsilon();
		double va = v[0]*a[0] + v[1]*a[1] + v[2]*a[2];
		double vb = v[0]*b[0] + v[1]*b[1] + v[2]*b[2];
		if( fabs(va-vb) > e ) 
		{
			if( va > vb ) 
				return 1;
			else
				return -1;
		}
		return 0;
	}
	bool operator() (HandleType a, HandleType b) const
	{
		if( a == InvalidHandle() || b == InvalidHandle() ) return a > b;
		double ca[3] = {0,0,0}, cb[3] = {0,0,0};
		m->GetGeometricData(a,CENTROID,ca);
		m->GetGeometricData(b,CENTROID,cb);
		return Compare(ca,cb) < 0;
	}	
};

Тогда упорядочивание узлов сведется к вызову:
std::sort(nodes.begin(),nodes.end(),OrderNodesAlongEdge(mesh,edge));

**Comment by APlenkin** [comment]
std::copy(other.v, other.v + 3, v);

**Comment by kirill-terekhov** [comment]
На грани - Face::Inside. Отдельной проверки для ребер нет.
