### ISSUE TITLE
Crash in ExchangeGhost

### ISSUE THREAD

**Issue by VKramarenko** [INMOST-DEV/INMOST#37]
возникли проблемы c распределением достаточно больших сеток. Мне надо посчитать задачу на ГеРе на сетке порядка нескольких миллионов. Но алгоритм построение Ghost ячеек не срабатывает и падает
с выводом

D:\work\IBRAE\GeRa\trunk\src\INMOST\Mesh\parallel.cpp:4960 marked for data 376 remote 374 on 0 from 2 found 464 marked ghost 376 total 840
D:\work\IBRAE\GeRa\trunk\src\INMOST\Mesh\parallel.cpp:5071 marked for data 1402 remote 1397 on 0 from 2
D:\work\IBRAE\GeRa\trunk\src\INMOST\Mesh\parallel.cpp:5200 marked for data 1443 remote 1441 on 0 from 2
D:\work\IBRAE\GeRa\trunk\src\INMOST\Mesh\parallel.cpp:4960 marked for data 369 remote 362 on 2 from 3 found 435 marked ghost 365 total 800
D:\work\IBRAE\GeRa\trunk\src\INMOST\Mesh\parallel.cpp:5071 marked for data 1354 remote 1337 on 2 from 3
D:\work\IBRAE\GeRa\trunk\src\INMOST\Mesh\parallel.cpp:5200 marked for data 1382 remote 1374 on 2 from 3

Изначально сетка в 1 миллион примерно распределяется с 1 процессора на 8 ( или 16 или 32) Падение происходит и на кластере и на Виндовс на локальной машине. При распределении на 2 и 4 процессора падения не происходит.

Ссылка на сетку 
https://drive.google.com/file/d/1EOVS0_Ep5al1qJtEq5O02lCSeWuJ8zDz/view?usp=sharing

**Comment by kirill-terekhov** [comment]
Попробовал
```
mpiexec -np 8 FVDiscr test_2_4mil_mesh.pmf
```
Все посчитало. Напишешь какой-нибудь код, чтобы воспроизвести проблему?

**Comment by VKramarenko** [comment]
Код приложил. На кластере в интерактивном режиме выдало вот это 
kramarenko@cl1n033:/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/No_Qt> mpirun -n 8 ./GeRa_no_Qt test_2_4mil_mesh.pmf
[main.zip](https://github.com/INMOST-DEV/INMOST/files/5402669/main.zip)


begin
begin
begin
begin
begin
begin
begin
begin
load test_2_4mil_mesh.pmf
load load test_2_4mil_mesh.pmf
load test_2_4mil_mesh.pmf
load test_2_4mil_mesh.pmf
load test_2_4mil_mesh.pmf
load test_2_4mil_mesh.pmf
load test_2_4mil_mesh.pmf
test_2_4mil_mesh.pmf
2883456
proc 0 num  2883456
proc 1 num  0
proc 2 num  0
proc 3 num  0
proc 4 num  0
proc 5 num  0
proc 6 num  0
proc 7 num  0
proc 0 num  380073
proc 1 num  391350
proc 2 num  402253
proc 3 num  365787
proc 4 num  278530
proc 5 num  364525
proc 6 num  397650
proc 7 num  303288
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:4960 marked for data 374 remote 372 on 1 from 2 found 742 marked ghost 372 total 1114
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:5071 marked for data 1127 remote 1122 on 1 from 2
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:5200 marked for data 1036 remote 1034 on 1 from 2
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:4960 marked for data 110 remote 104 on 0 from 4 found 196 marked ghost 110 total 306
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:5071 marked for data 339 remote 324 on 0 from 4
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:5200 marked for data 310 remote 304 on 0 from 4
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:4960 marked for data 483 remote 454 on 5 from 7 found 931 marked ghost 483 total 1414
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:5071 marked for data 1599 remote 1539 on 5 from 7
/data90t/biomath/kramarenko/trilinos_gera/GeRa/trunk/src/INMOST/Mesh/parallel.cpp:5200 marked for data 1537 remote 1514 on 5 from 7

**Comment by kirill-terekhov** [comment]
Да, воспроизвел

**Comment by kirill-terekhov** [comment]
Чинится двумя способами. Либо перед `ExchangeGhost` вызвать
```
mesh->SetEpsilon(1.0e-12);
```
либо вызвать
```
mesh->AssignGlobalID(CELL|FACE|EDGE|NODE);
```
Второе должно еще и побыстрее работать, но будет память тратить на индексы. Причина в том, что то ли сетка мелкая, то ли где-то наложение узлов происходит, и алгоритм считает, что какие-то из узлов совпали.

**Comment by kirill-terekhov** [comment]
Вообще с SetEpsilon лучше не связываться, а то слишком маленьким поставишь и оно перестанет находить совпадения. Вдруг там после пересылок точность падает. Лучше чтоб искало по индексам и все.
