### ISSUE TITLE
No possibility to set the ParMetis partitioning algorithm

### ISSUE THREAD

**Issue by chuck97** [INMOST-DEV/INMOST#38]
Столкнулся с такой особенностью использования встроенного ParMetis. 
Если в области достаточно много узлов, а процессоров не очень много, то метис иногда дает несколько подобластей в пользование процессору. Например вот на моей области с 4 процессорами:

![image](https://user-images.githubusercontent.com/19571622/98925277-d932df80-24e6-11eb-8f76-1102d21f2a34.png)

Есть информация, что есть возможность задавать вручную алгоритм разбиения, который запрещает подобластям быть несвязными: gpmetis -contig. Хотелось бы иметь возможность влиять на алгоритм разбиения из INMOST. 

Пример моей  [двумерной сетки](https://github.com/chuck97/INMOST_ICE/blob/master/Programs/test.pmf).

**Comment by kirill-terekhov** [comment]
К сожалению, у parmetis'а, который используется в INMOST'е нет такой функции. Она есть только у metis'а. 

Вот тут ответ разработчика: http://glaros.dtc.umn.edu/gkhome/node/1086

**Comment by kirill-terekhov** [comment]
Сергей, прикрутил вызов к Metis с указанной опцией, но не проверял. Ему необходимо, чтобы сетка была на одном процессоре. Попробуйте, пожалуйста, и напишите, если не работает.

**Comment by chuck97** [comment]
А можно пример кода вызова Metis со своими настройками?

**Comment by kirill-terekhov** [comment]
Сейчас из  класса Partitioner нет доступа к параметрам Metis'a, можно либо зайти внутрь и поменять их вручную тут:
https://github.com/INMOST-DEV/INMOST/blob/6b25c0b5508f4d63890f9ace1bbd14579cd450eb/Source/Partitioner/partitioner.cpp#L1237

Чуть более сложный вариант - скопировать себе весь вызов Metis'a отсюда
https://github.com/INMOST-DEV/INMOST/blob/6b25c0b5508f4d63890f9ace1bbd14579cd450eb/Source/Partitioner/partitioner.cpp#L454
досюда 
https://github.com/INMOST-DEV/INMOST/blob/6b25c0b5508f4d63890f9ace1bbd14579cd450eb/Source/Partitioner/partitioner.cpp#L1330
убрав все что относится к вызову Parmetis'а (это по define'ам видно).
