### ISSUE TITLE
Consider using wiki

### ISSUE THREAD

**Issue by kirill-terekhov** [INMOST-DEV/INMOST#4]
Check Wiki [https://github.com/INM-RAS/INMOST/wiki](https://github.com/INM-RAS/INMOST/wiki). Decide if you like it and whether it should be used instead of README.md files.

**Comment by kirill-terekhov** [comment]
Please take a look https://github.com/INM-RAS/INMOST/wiki/5400-Interval-Permutation

**Comment by a-a-danilov** [comment]
Started moving install instructions for Linux from README.md files to Wiki pages, sounds like a good idea. Thanks

**Comment by kirill-terekhov** [comment]
Disappointing that there is no latex/math support.
