### ISSUE TITLE
Is it possible to compile INMOST with FCBIILU2 solver ?

### ISSUE THREAD

**Issue by ryanbarisov** [INMOST-DEV/INMOST#42]
In order to compile INMOST with FCBIILU2 solver I use -DUSE_SOLVER_FCBIILU2=ON additional parameter in the command line CMake call. 
However, there should be the file Source/Solver/solver_fcbiilu2/fcbiilu2.cpp which is missing in repository, the FCBIILU2 solver build is thus skipped. 
This file is also present in the .gitignore.
I could not find any Git revision with this file present to compile FCBIILU2.

Is FCBIILU2 is not supported?

**Comment by kirill-terekhov** [comment]
It is proprietary.

**Comment by ryanbarisov** [comment]
So is it needed to be removed from INMOST in the future?
