### ISSUE TITLE
Сборка inmost с gcc 14.0.1 заканчивается ошибкой: error: no match for ‘operator=’ (operand types are ‘const INMOST::keyval_table’ and ‘const INMOST::keyval_table’)

### ISSUE THREAD

**Issue by rustamNSU** [INMOST-DEV/INMOST#46]
Здравствуйте!
На свежей сборки fedora 40 установлена версия gcc 14.0.1 (gcc (GCC) 14.0.1 20240411 (Red Hat 14.0.1-0)
), с которой не удается скомпилировать проект INMOST.
Более ранние версии gcc или clang справляются с  этой задачей, поэтому не критично.

Параметры сборки:
```bash
cmake -D'CMAKE_BUILD_TYPE=Release' \
      -D'CMAKE_CXX_STANDARD=17' \
      -D'USE_MPI=OFF' \
      -D'USE_OMP=OFF' \
      -D'USE_AUTODIFF=ON' \
      -D'COMPILE_EXAMPLES=ON' \
      -D'COMPILE_TESTS=ON' \
      ..
cmake --build . --parallel
```
коммит: a0f38c7a91164c7c4b61c66ba808f57fb031075a

![image](https://github.com/INMOST-DEV/INMOST/assets/54931369/faf1551b-4844-45b6-83ab-1a7f3ea93504)

**Comment by kirill-terekhov** [comment]
Это вроде поправил, во всех ветках
