### ISSUE TITLE
Метод Sparse::Matrix::Nonzeros() не помечен как константный

### ISSUE THREAD

**Issue by rustamNSU** [INMOST-DEV/INMOST#47]
Коммит: a0f38c7a91164c7c4b61c66ba808f57fb031075a

Метод Sparse::Matrix::Nonzeros() не помечен как константный, что затрудняет использование "const &"

![image](https://github.com/INMOST-DEV/INMOST/assets/54931369/b5359ea1-c409-4190-bcfe-fac68c347537)

**Comment by kirill-terekhov** [comment]
Изменения внесены во все ветки, спасибо!
