### ISSUE TITLE
Set const modifier for x in MatVec and MatVecTranspose methods of Sparse::Matrix

### ISSUE THREAD

**Issue by AlexLiogky** [INMOST-DEV/INMOST#48]
It seems that the implementation and meaning of the parameter x allows it to be made constant in Sparse::Matrix::MatVec and Sparse::Matrix:: MatVecTranspose

**Comment by kirill-terekhov** [comment]
Please commit suggested update to master, I'll propagate to other branches

**Comment by AlexLiogky** [comment]
Done
