### ISSUE TITLE
Rename organization

### ISSUE THREAD

**Issue by kirill-terekhov** [INMOST-DEV/INMOST#7]
I want to rename organization INM-RAS to INMOST. It will be similar to https://github.com/Trilinos/Trilinos

Reasons for renaming

* I don't represent INM-RAS
* May confuse people outside of INM-RAS who may be interested in developing INMOST

**Comment by a-a-danilov** [comment]
It is up to you to decide.
If we move the project, we should place a redirect to new address since the current address was already advertised in several places

**Comment by kirill-terekhov** [comment]
Since github.com/INMOST is already busy I've taken github.com/INMOST-DEV. Now URL is https://github.com/INMOST-DEV/INMOST. Old URL https://github.com/INM-RAS/INMOST will be active until somebody register under the name INM-RAS.


Please update git with:


`git remote set-url origin https://github.com/INMOST-DEV/INMOST.git`


Then check:


`git remote -v`


If you had a clone of wiki, setup this as well from wiki's folder:


`git remote set-url origin https://github.com/INMOST-DEV/INMOST.wiki.git`

**Comment by a-a-danilov** [comment]
Is it possible to register the name INM-RAS and ensure the redirect will be always active?

**Comment by kirill-terekhov** [comment]
You can create a user or an organization with the name INM-RAS


https://help.github.com/articles/creating-a-new-organization-account/
